"""Generates fuel_shock_model.xlsx: the unit economics + shock engine workbook.

All computed cells are live Excel formulas, so the workbook is fully editable
and auditable in Excel. Baseline country inputs are v0 estimates, clearly
flagged on the Inputs sheet, pending calibration against the data pipeline
and the CapitalIQ screen.

Run:  python excel/build_model.py
"""
import os

from openpyxl import Workbook
from openpyxl.formatting.rule import ColorScaleRule
from openpyxl.styles import Alignment, Border, Font, PatternFill, Side
from openpyxl.utils import get_column_letter

OUT = os.path.join(os.path.dirname(__file__), "fuel_shock_model.xlsx")

COUNTRIES = ["US", "India", "China", "Germany", "Brazil"]

# Parameter rows: (label, unit, [values per country], source note)
# Values are v0 ballpark estimates for a representative long-haul operator,
# to be replaced by pipeline/CIQ-calibrated numbers in week 2.
INPUTS = [
    ("Diesel pump price", "USD per liter", [0.95, 1.08, 1.05, 1.80, 1.10],
     "v0 estimate. Calibrate: EIA (US), PPAC (India), NDRC (China), Eurostat (Germany), ANP (Brazil)"),
    ("Crude-to-pump beta", "pct of crude move passed to pump", [0.36, 0.50, 0.60, 0.45, 0.65],
     "US CALIBRATED (regression of 13-week pct moves, Brent vs EIA diesel, 1994-2026, R2=0.51, beta=0.36; "
     "2015-on subset gives 0.33). Other four still v0 estimates, calibrate with Eurostat/PPAC/NDRC/ANP or Bloomberg"),
    ("Fuel efficiency", "km per liter", [2.80, 4.00, 3.00, 3.00, 2.90],
     "v0 estimate. US class 8 approx 6.5 mpg; lighter fleet mix in India"),
    ("Annual distance", "km per truck per year", [160000, 100000, 120000, 130000, 110000],
     "v0 estimate. Industry utilization benchmarks"),
    ("Driver wage incl employer costs", "USD per month", [5000, 380, 1250, 4400, 700],
     "v0 estimate. Calibrate: BLS OES (US), Eurostat (DE, incl social charges), industry reports (IN, CN, BR)"),
    ("Drivers per truck", "ratio", [1.10, 1.20, 1.10, 1.10, 1.10],
     "v0 estimate, accounts for relief drivers and turnover"),
    ("Maintenance and tires", "USD per km", [0.120, 0.050, 0.070, 0.110, 0.070],
     "v0 estimate. ATRI ops cost survey (US) as anchor"),
    ("Tolls and fees", "USD per km", [0.040, 0.030, 0.100, 0.150, 0.040],
     "v0 estimate. Germany Maut and China expressway tolls are major cost lines"),
    ("Insurance and permits", "USD per truck per year", [12000, 2500, 4000, 9000, 3500],
     "v0 estimate"),
    ("Financing and depreciation", "USD per truck per year", [28000, 6000, 10000, 24000, 11000],
     "v0 estimate. New tractor cost amortized approx 7 years; cheaper vehicles in IN, CN"),
    ("Overhead share of revenue", "pct", [0.08, 0.07, 0.07, 0.08, 0.08],
     "v0 estimate: admin, dispatch, facilities"),
    ("Revenue per km", "USD per km", [1.40, 0.58, 0.90, 1.85, 0.82],
     "v0 estimate calibrated so baseline margins land in the realistic 4 to 9 pct trucking band"),
    ("Cash buffer", "months of operating cost", [2.5, 1.5, 2.0, 3.0, 1.5],
     "v0 estimate by market maturity. Calibrate from CIQ cash and cost data"),
]

THIN = Side(style="thin", color="BFBFBF")
BORDER = Border(left=THIN, right=THIN, top=THIN, bottom=THIN)
HDR_FILL = PatternFill("solid", fgColor="1F3B4D")
HDR_FONT = Font(bold=True, color="FFFFFF")
NOTE_FONT = Font(italic=True, size=9, color="808080")
WARN_FILL = PatternFill("solid", fgColor="FFF2CC")


def style_header(ws, row, ncols, start_col=1):
    for c in range(start_col, start_col + ncols):
        cell = ws.cell(row=row, column=c)
        cell.fill = HDR_FILL
        cell.font = HDR_FONT
        cell.border = BORDER


def build_readme(wb):
    ws = wb.active
    ws.title = "README"
    lines = [
        ("Fuel Shock Stress Test: unit economics and shock engine", Font(bold=True, size=14)),
        ("", None),
        ("Question: what happens to a trucking operator's margin and cash position when crude oil spikes,", None),
        ("and what price increase restores profitability?", None),
        ("", None),
        ("Sheets:", Font(bold=True)),
        ("  Inputs: per-country baseline assumptions. ALL VALUES ARE v0 ESTIMATES pending calibration.", None),
        ("  UnitEconomics: per-km cost stack, baseline EBIT margin, fuel share of revenue (live formulas).", None),
        ("  ShockEngine: single-scenario stress test with adjustable shock, duration, pass-through, lag.", None),
        ("  SurvivalGrid: margin outcome across shock magnitude x duration for a selected country.", None),
        ("", None),
        ("Yellow cells are user inputs. Everything else is calculated.", None),
        ("Generated by excel/build_model.py. Safe to edit in Excel; regenerate to reset.", NOTE_FONT),
    ]
    for i, (text, font) in enumerate(lines, start=1):
        cell = ws.cell(row=i, column=1, value=text)
        if font:
            cell.font = font
    ws.column_dimensions["A"].width = 110


def build_inputs(wb):
    ws = wb.create_sheet("Inputs")
    ws.cell(row=1, column=1, value="Baseline assumptions per country (v0 estimates, to be calibrated)").font = Font(bold=True, size=12)
    headers = ["Parameter", "Unit"] + COUNTRIES + ["Source / calibration plan"]
    for j, h in enumerate(headers, start=1):
        ws.cell(row=3, column=j, value=h)
    style_header(ws, 3, len(headers))
    for i, (label, unit, vals, note) in enumerate(INPUTS, start=4):
        ws.cell(row=i, column=1, value=label).border = BORDER
        ws.cell(row=i, column=2, value=unit).border = BORDER
        for j, v in enumerate(vals, start=3):
            c = ws.cell(row=i, column=j, value=v)
            c.border = BORDER
            c.fill = WARN_FILL
        n = ws.cell(row=i, column=8, value=note)
        n.font = NOTE_FONT
        n.border = BORDER
    widths = [26, 26, 10, 10, 10, 10, 10, 70]
    for j, w in enumerate(widths, start=1):
        ws.column_dimensions[get_column_letter(j)].width = w


def build_unit_economics(wb):
    ws = wb.create_sheet("UnitEconomics")
    ws.cell(row=1, column=1, value="Per-km unit economics (all formulas reference Inputs)").font = Font(bold=True, size=12)
    headers = ["Line item (USD per km)"] + COUNTRIES
    for j, h in enumerate(headers, start=1):
        ws.cell(row=3, column=j, value=h)
    style_header(ws, 3, len(headers))

    # Inputs sheet rows: 4 diesel, 5 beta, 6 efficiency, 7 annual km, 8 wage,
    # 9 drivers/truck, 10 maint, 11 tolls, 12 insurance, 13 financing,
    # 14 overhead pct, 15 revenue per km, 16 cash buffer months
    rows = [
        ("Fuel", "=Inputs!{c}4/Inputs!{c}6"),
        ("Driver wages", "=Inputs!{c}8*12*Inputs!{c}9/Inputs!{c}7"),
        ("Maintenance and tires", "=Inputs!{c}10"),
        ("Tolls and fees", "=Inputs!{c}11"),
        ("Insurance and permits", "=Inputs!{c}12/Inputs!{c}7"),
        ("Financing and depreciation", "=Inputs!{c}13/Inputs!{c}7"),
        ("Overhead", "=Inputs!{c}14*Inputs!{c}15"),
    ]
    r = 4
    for label, fml in rows:
        ws.cell(row=r, column=1, value=label).border = BORDER
        for j in range(len(COUNTRIES)):
            col_letter = get_column_letter(3 + j)   # Inputs country cols start at C
            cell = ws.cell(row=r, column=2 + j, value=fml.format(c=col_letter))
            cell.border = BORDER
            cell.number_format = "0.000"
        r += 1

    summary = [
        ("Total cost per km", "=SUM({col}4:{col}10)", "0.000"),
        ("Revenue per km", "=Inputs!{ic}15", "0.000"),
        ("EBIT per km", "={col}12-{col}11", "0.000"),
        ("EBIT margin", "={col}13/{col}12", "0.0%"),
        ("Fuel share of revenue", "={col}4/{col}12", "0.0%"),
        ("Fuel share of total cost", "={col}4/{col}11", "0.0%"),
    ]
    for label, fml, numfmt in summary:
        ws.cell(row=r, column=1, value=label).border = BORDER
        ws.cell(row=r, column=1).font = Font(bold=(label in ("EBIT margin", "Fuel share of revenue")))
        for j in range(len(COUNTRIES)):
            col = get_column_letter(2 + j)
            icol = get_column_letter(3 + j)
            cell = ws.cell(row=r, column=2 + j, value=fml.format(col=col, ic=icol))
            cell.border = BORDER
            cell.number_format = numfmt
        r += 1

    ws.column_dimensions["A"].width = 28
    for j in range(2, 7):
        ws.column_dimensions[get_column_letter(j)].width = 12


def build_shock_engine(wb):
    ws = wb.create_sheet("ShockEngine")
    ws.cell(row=1, column=1, value="Shock scenario engine (yellow = your levers)").font = Font(bold=True, size=12)

    params = [
        ("Crude shock", 0.50, "0%", "pct increase in crude, e.g. 0.5 = +50%"),
        ("Duration", 6, "0", "months the spike lasts"),
        ("Pass-through", 0.50, "0%", "share of fuel increase recovered via surcharge, steady state"),
        ("Surcharge lag", 2, "0", "months before surcharges kick in"),
    ]
    for i, (label, val, fmt, note) in enumerate(params, start=3):
        ws.cell(row=i, column=1, value=label).font = Font(bold=True)
        c = ws.cell(row=i, column=2, value=val)
        c.fill = WARN_FILL
        c.number_format = fmt
        c.border = BORDER
        ws.cell(row=i, column=3, value=note).font = NOTE_FONT

    headers = ["Metric"] + COUNTRIES
    for j, h in enumerate(headers, start=1):
        ws.cell(row=8, column=j, value=h)
    style_header(ws, 8, len(headers))

    # Effective pass-through over the duration accounts for the lag window.
    rows = [
        ("Pump price shock", "=$B$3*Inputs!{ic}5", "0.0%"),
        ("Effective pass-through", "=$B$5*MAX(0,($B$4-$B$6)/$B$4)", "0.0%"),
        ("Margin hit (pp of revenue)", "=UnitEconomics!{c}15*{c}9*(1-{c}10)", "0.0%"),
        ("Shocked EBIT margin", "=UnitEconomics!{c}14-{c}11", "0.0%"),
        ("Monthly burn if negative (USD/truck)", "=MAX(0,-{c}12)*Inputs!{ic}15*Inputs!{ic}7/12", "#,##0"),
        ("Cash available (USD/truck)", "=Inputs!{ic}16*UnitEconomics!{c}11*Inputs!{ic}7/12", "#,##0"),
        ("Months to cash breach", "=IF({c}12>=0,\"survives\",IF({c}13=0,\"survives\",{c}14/{c}13))", "0.0"),
        ("Price increase to restore margin", "={c}11", "0.0%"),
    ]
    r = 9
    for label, fml, numfmt in rows:
        ws.cell(row=r, column=1, value=label).border = BORDER
        for j in range(len(COUNTRIES)):
            col = get_column_letter(2 + j)
            icol = get_column_letter(3 + j)
            cell = ws.cell(row=r, column=2 + j, value=fml.format(c=col, ic=icol))
            cell.border = BORDER
            cell.number_format = numfmt
        r += 1
    ws.cell(row=r + 1, column=1,
            value="Note: price increase to restore margin equals the unrecovered fuel hit as a share of revenue; "
                  "assumes volumes hold, which is the next refinement (demand elasticity).").font = NOTE_FONT

    ws.column_dimensions["A"].width = 34
    for j in range(2, 7):
        ws.column_dimensions[get_column_letter(j)].width = 13
    ws.column_dimensions["C"].width = 13


def build_survival_grid(wb):
    ws = wb.create_sheet("SurvivalGrid")
    ws.cell(row=1, column=1, value="Shocked EBIT margin: crude shock magnitude x duration").font = Font(bold=True, size=12)
    ws.cell(row=3, column=1, value="Country (1=US 2=India 3=China 4=Germany 5=Brazil)").font = Font(bold=True)
    sel = ws.cell(row=3, column=6, value=1)
    sel.fill = WARN_FILL
    sel.border = BORDER
    ws.cell(row=4, column=1, value="Pass-through").font = Font(bold=True)
    pt = ws.cell(row=4, column=6, value=0.5)
    pt.fill = WARN_FILL
    pt.number_format = "0%"
    pt.border = BORDER
    ws.cell(row=5, column=1, value="Surcharge lag (months)").font = Font(bold=True)
    lag = ws.cell(row=5, column=6, value=2)
    lag.fill = WARN_FILL
    lag.border = BORDER

    durations = [3, 6, 9, 12]
    shocks = [0.10, 0.20, 0.30, 0.40, 0.50, 0.75, 1.00]

    ws.cell(row=7, column=1, value="Crude shock \\ Duration (months)")
    style_header(ws, 7, 1 + len(durations))
    for j, d in enumerate(durations, start=2):
        ws.cell(row=7, column=j, value=d)

    for i, s in enumerate(shocks, start=8):
        c = ws.cell(row=i, column=1, value=s)
        c.number_format = "0%"
        c.border = BORDER
        c.font = Font(bold=True)
        for j, d in enumerate(durations, start=2):
            # margin0 - fuelShareRev * shock*beta * (1 - pass*max(0,(dur-lag)/dur))
            fml = (
                f"=INDEX(UnitEconomics!$B$14:$F$14,$F$3)"
                f"-INDEX(UnitEconomics!$B$15:$F$15,$F$3)"
                f"*$A{i}*INDEX(Inputs!$C$5:$G$5,$F$3)"
                f"*(1-$F$4*MAX(0,({get_column_letter(j)}$7-$F$5)/{get_column_letter(j)}$7))"
            )
            cell = ws.cell(row=i, column=j, value=fml)
            cell.number_format = "0.0%"
            cell.border = BORDER

    rng = f"B8:{get_column_letter(1 + len(durations))}{7 + len(shocks)}"
    ws.conditional_formatting.add(
        rng,
        ColorScaleRule(start_type="num", start_value=-0.10, start_color="D03B3B",
                       mid_type="num", mid_value=0.0, mid_color="FAB219",
                       end_type="num", end_value=0.08, end_color="0CA30C"),
    )
    ws.cell(row=7 + len(shocks) + 2, column=1,
            value="Red: margin below zero (burning cash). Amber: near breakeven. Green: profitable.").font = NOTE_FONT
    ws.column_dimensions["A"].width = 32


def main():
    wb = Workbook()
    build_readme(wb)
    build_inputs(wb)
    build_unit_economics(wb)
    build_shock_engine(wb)
    build_survival_grid(wb)
    wb.save(OUT)
    print(f"wrote {OUT}")


if __name__ == "__main__":
    main()
